---
- name: Configurar NGINX como proxy para tres rutas
  hosts: localhost
  gather_facts: false
  vars:
    project_root: "{{ playbook_dir }}/.."
    nginx_conf_host: "{{ project_root }}/host_volumes/nginx_conf"
    web_conf_host: "{{ project_root }}/host_volumes/web"
    nginx_container: "nginx_proxy"

    app1_web: "{{ project_root }}/host_volumes/app1_web"
    app2_web: "{{ project_root }}/host_volumes/app2_web"
    app3_web: "{{ project_root }}/host_volumes/app3_web"

  tasks:
    - name: Crear las carpetas
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        mode: "0755"
      loop:
        - "{{ nginx_conf_host }}"
        - "{{ web_conf_host }}"
        - "{{ app1_web }}"
        - "{{ app2_web }}"
        - "{{ app3_web }}"
    - name: Copiar la pagina web
      ansible.builtin.copy:
        src: "files/index.html"
        dest: "{{web_conf_host}}/index.html"
        mode: "0644"

    - name: Copiar la config de NGINX
      ansible.builtin.copy:
        src: "templates/nginx.conf"
        dest: "{{nginx_conf_host}}/default.conf"
        mode: "0644"

    - name: Renderizar index para app1
      ansible.builtin.template:
        src: "templates/app_index.html.j2"
        dest: "{{ app1_web }}/index.html"
        mode: "0644"
      vars:
        app_name: "app1"

    - name: Renderizar index para app2
      ansible.builtin.template:
        src: "templates/app_index.html.j2"
        dest: "{{ app2_web }}/index.html"
        mode: "0644"
      vars:
        app_name: "app2"

    - name: Renderizar index para app3
      ansible.builtin.template:
        src: "templates/app_index.html.j2"
        dest: "{{ app3_web }}/index.html"
        mode: "0644"
      vars:
        app_name: "app3"

    - name: Reiniciar contenedor si fallo la recarga
      ansible.builtin.command: >
        docker exec {{nginx_container}} nginx -s reload
      register: reload_result
      changed_when: reload_result.rc == 0
      failed_when: false